// <auto-generated />
using System;
using AudtingAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudtingAPI.Migrations
{
    [DbContext(typeof(AuditDB))]
    [Migration("20231122194524_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AudtingAPI.Models.AuditModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeModelId");

                    b.HasIndex("UserModelId");

                    b.ToTable("AuditModels");
                });

            modelBuilder.Entity("AudtingAPI.Models.DepartmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepartmentModels");
                });

            modelBuilder.Entity("AudtingAPI.Models.EmployeeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentModelId");

                    b.ToTable("EmployeeModels");
                });

            modelBuilder.Entity("AudtingAPI.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("AudtingAPI.Models.AuditModel", b =>
                {
                    b.HasOne("AudtingAPI.Models.EmployeeModel", "EemployeeModel")
                        .WithMany("AuditModels")
                        .HasForeignKey("EmployeeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudtingAPI.Models.UserModel", "UserModel")
                        .WithMany("AuditModels")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EemployeeModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("AudtingAPI.Models.EmployeeModel", b =>
                {
                    b.HasOne("AudtingAPI.Models.DepartmentModel", "DepartmentModel")
                        .WithMany("employeeModels")
                        .HasForeignKey("DepartmentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentModel");
                });

            modelBuilder.Entity("AudtingAPI.Models.DepartmentModel", b =>
                {
                    b.Navigation("employeeModels");
                });

            modelBuilder.Entity("AudtingAPI.Models.EmployeeModel", b =>
                {
                    b.Navigation("AuditModels");
                });

            modelBuilder.Entity("AudtingAPI.Models.UserModel", b =>
                {
                    b.Navigation("AuditModels");
                });
#pragma warning restore 612, 618
        }
    }
}
